# Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
 def divide(x, y): 
    try: 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ")  
divide(3, 0) 


Sorry ! You are dividing by zero 


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [2]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)


Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task 2:
1.
 Write a function so that the columns of the output matrix are powers of the input vector

In [10]:
import numpy as np 
  
# input_array 
arr1 = ([[ 1,  1,  1],
         [ 4,  2,  1],
         [ 9,  3,  1],
         [25,  5,  1]]) 
arr2 = ([[ 1,  1,  1],
         [ 4,  2,  1],
         [ 9,  3,  1],
         [25,  5,  1]])
print ("arr1         : ", arr1) 
print ("arr1         : ", arr2) 
  
# output_array 
out = np.power(arr1, arr2) 
print ("\nOutput array : ", out)

arr1         :  [[1, 1, 1], [4, 2, 1], [9, 3, 1], [25, 5, 1]]
arr1         :  [[1, 1, 1], [4, 2, 1], [9, 3, 1], [25, 5, 1]]

Output array :  [[         1          1          1]
 [       256          4          1]
 [ 387420489         27          1]
 [1296002393       3125          1]]
